frequency: 116

sensor_timeout: 0.1
two_d_mode: true
publish_tf: true

odom0: /odom
odom0_config: [true, true, false,
		false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10

imu0: /imu
imu0_config: [false, false, false, 
		true, true, false,
              false, false, false, 
              false, false, true,
              false, false, false]
              
imu0_differential: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

process_noise_covariance: [0.05, 0, 0, 0, 0, 0,
                           0, 0.05, 0, 0, 0, 0,
                           0, 0, 0.05, 0, 0, 0,
                           0, 0, 0, 0.05, 0, 0,
                           0, 0, 0, 0, 0.05, 0,
                           0, 0, 0, 0, 0, 0.05]

initial_estimate_covariance: [1e-9, 0, 0, 0, 0, 0,
                              0, 1e-9, 0, 0, 0, 0,
                              0, 0, 1e-9, 0, 0, 0,
                              0, 0, 0, 1e-9, 0, 0,
                              0, 0, 0, 0, 1e-9, 0,
                              0, 0, 0, 0, 0, 1e-9]

map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom

