frequency: 30

sensor_timeout: 0.2
two_d_mode: true
publish_tf: false
map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: map

odom0: /odom
odom0_config: [false, false, false,
              false, false, false,
              true, true, false,
              false, false, true,
              false, false, false]

odom0_relative: false

imu0: /imu
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              true, true, false,
              false, false, false]
              
imu0_relative: true
imu0_remove_gravitational_acceleration: true

gt0: /gtInfo
gt0_config: [true, true, false,  # X, Y, Z positions
              false, false, true, # Roll, Pitch, Yaw orientations
              false, false, false, # X, Y, Z velocities
              false, false, false, # Roll, Pitch, Yaw angular velocities
              false, false, false] # Linear acceleration (if available)
gt0_differential: false
